### ISSUE TITLE
Provide examples for practical use.

### ISSUE THREAD

**Issue by aiji42** [aiji42/remix-esbuild-override#10]
- [x] [emotion(styled) x cloudflare](https://github.com/aiji42/remix-esbuild-override/tree/main/examples/emotion-cloudflare)
- [x] [emotion(css props) x cloudflare](https://github.com/aiji42/remix-esbuild-override/tree/main/examples/emotion-css-props-cloudflare)
- [x] [chakra-ui x cloudflare](https://github.com/aiji42/remix-esbuild-override/tree/main/examples/chakra-ui-cloudflare)
- [ ] preact x Runtime is anywhere
- [x] ~~supabase-js x cloudflare~~
    - With the next release of remix, changes to mainFields will no longer be necessary. https://github.com/remix-run/remix/pull/1977
- [x] [mantine x cloudflare](https://github.com/aiji42/remix-esbuild-override/tree/main/examples/mantine-cloudflare)
- [ ] stylus x Runtime is anywhere
- [x] [linaria x Runtime is anywhare](https://github.com/aiji42/remix-esbuild-override/tree/main/examples/linaria) https://github.com/remix-run/remix/issues/1619
- [ ] vanilla-extract x Runtime is anywhere https://github.com/seek-oss/vanilla-extract/discussions/178
- [ ] ~~Buffer polyfill (using @magic-sdk/admin v[1.3.4](https://www.npmjs.com/package/@magic-sdk/admin/v/1.3.4))~~

If you have other needs, let me know.

**Comment by 3x071c** [comment]
@aiji42 Hi, do you know by chance if it's possible to use `remix-esbuild-override` to make libraries that implicitly use Node.js `buffer` work, e.g. by making them import the browser-compatible [buffer](https://npmjs.com/buffer) polyfill instead? Context: I've been trying to get `@magic-sdk/admin` ([Magic](https://magic.link)) to work, which uses `keccak` internally somewhere, probably as part of the `ethereumjs-util` package (ethereumjs/ethereumjs-monorepo#1062).

**Comment by aiji42** [comment]
@3x071c I will have to try it out to find out. Could you please share with me the minimum repository to reproduce that issue?

**Comment by 3x071c** [comment]
Sure: [3x071c/remix-cf-buffer](https://github.com/3x071c/remix-cf-buffer). I should probably ask if a proper fix can be implemented at `@magic-sdk/admin`, `ethereumjs-util` and `keccak`, but for now I'm just eager to know if this can be worked around.

**Comment by 3x071c** [comment]
@aiji42 Sure: [3x071c/remix-cf-buffer](https://github.com/3x071c/remix-cf-buffer). I should probably ask if a proper fix can be implemented at `@magic-sdk/admin`, `ethereumjs-util` and `keccak`, but for now I'm just eager to know if this can be worked around.

**Comment by 3x071c** [comment]
Update: `@magic-sdk/admin` had a big update and is environment agnostic now 🥳

**Comment by aiji42** [comment]
Very timely update! It is best to have official support.

It looks interesting and I would like to try polyfilling Buffer when I have some spare time. If it works, I will publish it as one of the templates.

**Comment by aiji42** [comment]
@3x071c In the meantime, polyfilingl is complete (although if you upgrade @magic-sdk/admin, you don't need this PR anymore). 
https://github.com/3x071c/remix-cf-buffer/pull/1

**Comment by aiji42** [comment]
The process of creating some examples made me realize that the majority of the errors are due to the fact that the library is Buffer-dependent.
I believe Remix should be supported so that Buffer is automatically polyfilled when cloudflare is selected at runtime.
I will open a discussion soon.
