### ISSUE TITLE
Linaria example is outdated

### ISSUE THREAD

**Issue by zardoy** [aiji42/remix-esbuild-override#31]
In linaria folder:

- if using with provided deps from lockfile everything is ok
- using with latest `@remix-run/*` (currently 1.4.0 -> 1.7.0) deps breaks application with following error:
```log
Unexpected Server Error

ReferenceError: React is not defined
```
- updating linaria deps to latest (`pnpm up "@linaria/*" -L`) breaks build

Alternative str:

1. `create-remix` with basic setup
2. Follow steps from linaria example
3. Try to start

**Comment by aiji42** [comment]
Sorry, linaria is no longer supported by this repository.

**Comment by redbugz** [comment]
I created an issue for the `ReferenceError: React is not defined`:
https://github.com/callstack/linaria/issues/1338
