### ISSUE TITLE
Not working with Remix Run 1.7.6

### ISSUE THREAD

**Issue by uceumice** [aiji42/remix-esbuild-override#36]

**Comment by aiji42** [comment]
I have tried it with the latest Remix (v1.7.6) project and it seems to work fine without any problems.
Please check if there are any mistakes in setup or usage.

**Comment by uceumice** [comment]
Hey, sorry for the false entry. I have no idea how to call this issue, but in a nutshell, when working with `pnpm`, under certainly resolved dependency tree, the patch by `remix-esbuild-override` does not apply, resulting in common process/Buffer errors. I will create a codesandbox or stackblitz project as an example shortly.
